file:
  upload-dir: /files/upload-dir #diretório para salvar os arquivos 
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/familybudgetcontrol?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: "*"  #inclui todos endpoints e habilitar detalhes do health
  endpoint:
    health:
      show-details: always

   