cors:
  originPatterns: http://localhost:8080,https://familybudgetcontrol.com.br
file:
  upload-dir: /files/upload-dir #diretório para salvar os arquivos
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: 3600000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: $(DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
management:
  endpoints:
    web:
      exposure:
        include: "*"  #inclui todos endpoints e habilitar detalhes do health
  endpoint:
    health:
      show-details: always
springdoc:
  pathsToMatch: #para restrigir as descrições
  - /budget-control/**
  swagger-ui:
    use-root-path: true #acessível diretamente do caminho raiz 